[workspace]
resolver = "2"
members = [ "crates/brioche-autowrap",
    "crates/brioche-ld",
    "crates/brioche-packed-plain-exec",
    "crates/brioche-packed-userland-exec",
    "crates/brioche-packer", "crates/brioche-resources",
    "crates/runnable",
    "crates/runnable-core",
    "crates/start-runnable",
]

[workspace.dependencies]
brioche-pack = { git = "https://github.com/brioche-dev/brioche.git", default-features = false }

[profile.release-tiny]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"
