[package]
name = "brioche-ld"
version = "0.1.1"
edition = "2021"

[dependencies]
brioche-autopack = { path = "../brioche-autopack" }
brioche-pack = { workspace = true }
brioche-resources = { path = "../brioche-resources" }
bstr = "1.9.1"
eyre = "0.6.12"
thiserror = "1.0.62"
