[package]
name = "brioche-packed-userland-exec"
version = "0.1.1"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
brioche-pack = { workspace = true }
brioche-resources = { path = "../brioche-resources" }
bstr = "1.9.1"
cfg-if = "1.0.0"
libc = "0.2.155"
thiserror = "1.0.62"

[target.'cfg(target_os = "linux")'.dependencies]
userland-execve = "0.2.0"
