[package]
name = "brioche-packed-userland-exec"
version = "0.1.1"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
libc = "0.2.151"

[target.'cfg(target_os = "linux")'.dependencies]
userland-execve = "0.2.0"
