[package]
name = "runnable-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
brioche-resources = { path = "../brioche-resources" }
bstr = "1.9.1"
schemars = "0.8.21"
serde = { version = "1.0.204", features = ["derive"] }
serde_with = { version = "3.8.3", features = ["schemars_0_8"] }
thiserror = "1.0.61"
tick-encoding = "0.1.2"
