[package]
name = "start-runnable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1.9.1"
cfg-if = "1.0.0"
runnable-core = { path = "../runnable-core" }
thiserror = "1.0.61"
