[package]
name = "brioche-autowrap"
version = "0.1.0"
edition = "2021"

[dependencies]
brioche-pack = { workspace = true }
brioche-resources = { path = "../brioche-resources" }
bstr = "1.9.1"
goblin = "0.8.2"
thiserror = "1.0.61"
