[package]
name = "brioche-packed-plain-exec"
version = "0.1.1"
edition = "2021"

[dependencies]
brioche-pack = { workspace = true }
brioche-resources = { path = "../brioche-resources" }
bstr = "1.9.1"
libc = "0.2.155"
runnable-core = { path = "../runnable-core" }
serde_json = "1.0.120"
thiserror = "1.0.62"
